services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: python -m fastapi run --app-dir app --app main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - ENVIRONMENT=development
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27015:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 